# Generated by Django 4.0 on 2021-12-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=40)),
                ('company_about', models.TextField(blank=True)),
                ('company_phone', models.CharField(blank=True, max_length=30)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_logo', models.ImageField(blank=True, upload_to='')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
