# Generated by Django 4.0 on 2021-12-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0003_company_comapny_category_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comapny_category',
            field=models.CharField(choices=[('Internet Shop', 'Internet Shop'), ('SuperMarket', 'SuperMarket'), ('Shopping center', 'Shopping center'), ('Furniture Shop', 'Furniture Shop'), ('DEFAULT', 'DEFAULT')], default='DF', max_length=40),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20),
        ),
    ]
